// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qokecmatwbbtkdmgmief.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFva2VjbWF0d2JidGtkbWdtaWVmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMyNTk1ODcsImV4cCI6MjA1ODgzNTU4N30.V4SuxF31TJQ6zve1JAoWIgf27OZliE67SvJmxo0nnvQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);